### ISSUE TITLE
 Cannot find module './query.gql'.ts(2307) #6 

### ISSUE THREAD

**Issue by samgermain** [NWRichmond/gatsby-plugin-graphql-loader#5]
Following the [tutorial on the gatsby website for gatsby-plugin-graphql-loader](https://www.gatsbyjs.org/packages/gatsby-plugin-graphql-loader/)

Trying

`import query = require("./query.gql")`

or

`import query from "./query.gql"`

And have my corresponding ./query.gql file in the same folder

```
query HeaderQuery {
    allImageSharp(filter: {id: {eq: "some-id"}}) {
        edges {
            node {
                sizes {
                    sizes
                    srcSet
                    src
                    aspectRatio
                }
            }
        }
    }
}

```
and

```
  plugins: [
      ...       
      `gatsby-plugin-graphql-loader`
      ...
  ],
```

in my gatsby-config.js

------------------------------------

**Note**: I am not using `import { useQuery } from "@apollo/react-hooks";` because I just wanted to use `useStaticQuery( query )`. Is Apollo necessary or is useStaticQuery fine?

**Comment by NWRichmond** [comment]
Hi @samgermain!

`gatsby-plugin-graphql-loader` doesn't work with `useStaticQuery`, unfortunately. `useStaticQuery` is used to run queries at build time. As per the [`gatsby-plugin-graphql-loader` docs](https://github.com/NWRichmond/gatsby-plugin-graphql-loader#this-is-not-for):

> **This is not for**:
> 
> Loading queries used at build time.
>
> For more information on the distinction between runtime vs. build time, see the [Gatsby docs](https://www.gatsbyjs.org/docs/overview-of-the-gatsby-build-process/).

`gatsby-plugin-graphql-loader` doesn't have to be used with [`@apollo/react-hooks`](https://www.npmjs.com/package/@apollo/react-hooks), but it does have to be used with some HTTP client that operates in the browser runtime. Both [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch) and [`axios`](https://www.npmjs.com/package/axios) are examples of tools other than `@apollo/react-hooks` that can be used to perform a GraphQL query (as a `POST` request).

A common use case for `gatsby-plugin-graphql-loader` is loading queries that are used to fetch a user's information to be shown on an account page. You can't build that account page ahead of time, so it's perfect for a client-side GraphQL query with `axios`, `@apollo/react-hooks`, or similar.

I hope this helps explain why `gatsby-plugin-graphql-loader` wasn't working for your use case.

Also...this is just general advice, not specific to `gatsby-plugin-graphql-loader`...take care not to mix CommonJS syntax (`require()`) with ES Modules syntax (`import`). To use the examples you provided,

> `import query from "./query.gql"`

is valid, whereas:

> `import query = require("./query.gql")`

is not.
